export const Users = [
  {
    id: 1,
    username: 'travelwithsara',
    fullName: 'Sara Lee',
    profilePicture: 'https://randomuser.me/api/portraits/women/10.jpg',
    bio: 'Wanderlust. Exploring the world one city at a time.',
    followers: 15000,
    following: 300,
    posts: 180,
    isVerified: false,
  },
  {
    id: 2,
    username: 'fitguy_jake',
    fullName: 'Jake Williams',
    profilePicture: 'https://randomuser.me/api/portraits/men/10.jpg',
    bio: 'Fitness junkie 💪 | Helping you stay healthy',
    followers: 12500,
    following: 200,
    posts: 220,
    isVerified: false,
  },
  {
    id: 3,
    username: 'urbanchef_liz',
    fullName: 'Liz Huang',
    profilePicture: 'https://randomuser.me/api/portraits/women/12.jpg',
    bio: 'Professional chef 🍲 | NYC | Food lover',
    followers: 30000,
    following: 450,
    posts: 560,
    isVerified: true,
  },
  {
    id: 4,
    username: 'photoby_marc',
    fullName: 'Marc Spencer',
    profilePicture: 'https://randomuser.me/api/portraits/men/12.jpg',
    bio: 'Photographer 📸 | Capturing moments | Worldwide',
    followers: 6000,
    following: 150,
    posts: 410,
    isVerified: false,
  },
  {
    id: 5,
    username: 'yoga_journey',
    fullName: 'Priya Gupta',
    profilePicture: 'https://randomuser.me/api/portraits/women/15.jpg',
    bio: 'Yoga instructor | Wellness advocate 🌱',
    followers: 23000,
    following: 180,
    posts: 320,
    isVerified: true,
  },
  {
    id: 6,
    username: 'techgeek_dave',
    fullName: 'Dave Lee',
    profilePicture: 'https://randomuser.me/api/portraits/men/15.jpg',
    bio: 'Tech reviews | Gadget lover 🔌 | Simplifying tech',
    followers: 48000,
    following: 800,
    posts: 540,
    isVerified: true,
  },
  {
    id: 7,
    username: 'fitness_queen_anna',
    fullName: 'Anna Perez',
    profilePicture: 'https://randomuser.me/api/portraits/women/18.jpg',
    bio: 'Fitness trainer 💃 | Passionate about healthy living',
    followers: 12000,
    following: 300,
    posts: 150,
    isVerified: false,
  },
  {
    id: 8,
    username: 'fashionista_zoe',
    fullName: 'Zoe Carter',
    profilePicture: 'https://randomuser.me/api/portraits/women/20.jpg',
    bio: 'Fashion blogger | NYC | Inspiring outfits 🌟',
    followers: 34000,
    following: 420,
    posts: 670,
    isVerified: true,
  },
  {
    id: 9,
    username: 'gamer_johnny',
    fullName: 'Johnny Cruz',
    profilePicture: 'https://randomuser.me/api/portraits/men/18.jpg',
    bio: "Gaming streamer 🎮 | Let's play together!",
    followers: 18000,
    following: 250,
    posts: 330,
    isVerified: false,
  },
  {
    id: 10,
    username: 'adventures_kate',
    fullName: 'Kate Robinson',
    profilePicture: 'https://randomuser.me/api/portraits/women/25.jpg',
    bio: 'Adventure seeker 🌄 | Travel | Outdoors',
    followers: 22000,
    following: 390,
    posts: 470,
    isVerified: false,
  },
];

export const posts = [
  {
    postId: 1,
    userId: 1,
    username: 'travelwithsara',
    caption: 'Sunsets in Santorini are something else 🌅 #wanderlust #sunset',
    image:
      'https://dfstudio-d420.kxcdn.com/wordpress/wp-content/uploads/2019/06/digital_camera_photo-1080x675.jpg',
    likes: 2100,
    comments: 150,
    timestamp: '2023-10-14T17:45:00Z',
    location: 'Santorini, Greece',
    isLikedByUser: false,
  },
  {
    postId: 2,
    userId: 2,
    username: 'fitguy_jake',
    caption: 'Push yourself every day! 💪 #NoPainNoGain #FitnessJourney',
    image: 'https://example.com/images/gym-session.jpg',
    likes: 1700,
    comments: 45,
    timestamp: '2023-10-15T12:30:00Z',
    location: "Gold's Gym",
    isLikedByUser: true,
  },
  {
    postId: 3,
    userId: 3,
    username: 'urbanchef_liz',
    caption: 'Mastered a new dish today 🍲✨ #ChefLife #Foodie',
    image: 'https://example.com/images/gourmet-dish.jpg',
    likes: 3200,
    comments: 85,
    timestamp: '2023-10-16T18:10:00Z',
    location: 'NYC',
    isLikedByUser: false,
  },
  {
    postId: 4,
    userId: 4,
    username: 'photoby_marc',
    caption: 'Caught a beautiful moment in the mountains 🏞️ #NaturePhotography',
    image: 'https://example.com/images/mountain-view.jpg',
    likes: 2500,
    comments: 70,
    timestamp: '2023-10-17T10:00:00Z',
    location: 'Rocky Mountains',
    isLikedByUser: true,
  },
  {
    postId: 5,
    userId: 5,
    username: 'yoga_journey',
    caption:
      'Morning yoga flows to start the day right 🧘‍♀️ #Mindfulness #YogaLife',
    image: 'https://example.com/images/yoga-sunrise.jpg',
    likes: 2800,
    comments: 65,
    timestamp: '2023-10-18T07:00:00Z',
    location: 'Los Angeles',
    isLikedByUser: false,
  },
  {
    postId: 6,
    userId: 6,
    username: 'techgeek_dave',
    caption: 'Unboxing the latest gadget! 🔌 #TechReview',
    image: 'https://example.com/images/gadget-unboxing.jpg',
    likes: 4300,
    comments: 120,
    timestamp: '2023-10-19T15:30:00Z',
    location: 'San Francisco',
    isLikedByUser: false,
  },
  {
    postId: 7,
    userId: 7,
    username: 'fitness_queen_anna',
    caption: 'A perfect day to crush some goals 💥 #FitnessMotivation',
    image: 'https://example.com/images/running-track.jpg',
    likes: 2200,
    comments: 40,
    timestamp: '2023-10-20T08:00:00Z',
    location: 'Central Park, NYC',
    isLikedByUser: true,
  },
  {
    postId: 8,
    userId: 8,
    username: 'fashionista_zoe',
    caption: 'Fall fashion trends are here 🍂✨ #FallFashion',
    image: 'https://example.com/images/fall-outfit.jpg',
    likes: 3900,
    comments: 110,
    timestamp: '2023-10-21T11:00:00Z',
    location: 'SoHo, NYC',
    isLikedByUser: false,
  },
  {
    postId: 9,
    userId: 9,
    username: 'gamer_johnny',
    caption: "New game drop! Who's excited? 🎮 #GamerLife",
    image: 'https://example.com/images/game-cover.jpg',
    likes: 1500,
    comments: 55,
    timestamp: '2023-10-22T21:00:00Z',
    location: 'Online',
    isLikedByUser: true,
  },
  {
    postId: 10,
    userId: 10,
    username: 'adventures_kate',
    caption: 'Exploring hidden gems 🏕️ #Wanderlust',
    image: 'https://example.com/images/hidden-gem.jpg',
    likes: 2700,
    comments: 100,
    timestamp: '2023-10-23T13:30:00Z',
    location: 'Yosemite National Park',
    isLikedByUser: false,
  },
];
